apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  {{- tpl (.Files.Glob "files/content/*").AsConfig . | nindent 2 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  {{- tpl (.Files.Glob "files/config/*").AsConfig . | nindent 2 }}
