proxy:
   secretToken: "token"
   service:
     nodePorts:
       http: 32000

singleuser:
   storage:
       dynamic:
          storageClass: nfs-client

auth:
  admin:
    users:
      - salho

hub:
  image:
    name: grainerm/jupyterhub
    tag: latest
  extraConfig: |
    import os
    import socket
    import subprocess
    from jupyterhub.spawner import Spawner
    
    c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'
    c.JupyterHub.cleanup_servers = False

    c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
    c.LDAPAuthenticator.server_address = 'ldaps://ldaps_ip'
    c.LDAPAuthenticator.bind_dn_template = ['cn={username},ou=IMA16,ou=IMA,OU=Studenten,OU=Benutzer,OU=Graz,OU=Technikum,dc=technikum,dc=fh-joanneum,dc=local', 'cn={username},ou=IMA,OU=Personal,OU=Benutzer,OU=Graz,OU=Technikum,dc=technikum,dc=fh-joanneum,dc=local', 'CN=kuberhub,CN=Users,DC=technikum,DC=fh-joanneum,DC=local']
    c.LDAPAuthenticator.user_search_base = 'ou=technikum,dc=technikum,dc=fh-joanneum,dc=local'
    c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
    c.LDAPAuthenticator.escape_userdn = False
 
    def chooseImage(spawner):
        username = spawner.user.name 
        userdn = os.environ.get(username)
      
        path_ima = '/tmp/exchange/ima/nbgrader_config.py'
        path_dat = '/tmp/exchange/dat/nbgrader_config.py'
        
        # if('Personal' in userdn and 'IMA' in userdn):
        if('IMA16' in userdn):
            spawner.environment = {
                'NB_UID' : '2000',
                'TEACHER_GID' : '200',
                'CONFIGPATH': path_ima
            }
            
        #elif('IMA18' in userdn):
        elif('kuberhub' in userdn):
            spawner.environment = {
                'NB_UID' : '2001',
                'NB_GID' : '201',
                'CONFIGPATH': path_ima
            }
            
        elif('DAT' in userdn and 'Personal' in userdn):
        #elif('grainerm15' in userdn):
            spawner.environment = {
                'NB_UID': '2000',
                'TEACHER_GID': '200',
                'CONFIGPATH': path_dat
            }
            
        #elif('DAT18' in userdn):
        elif('grainerm15' in userdn):
            spawner.environment = {
                'NB_UID': '2001',
                'NB_GID': '201',
                'CONFIGPATH': path_dat
            }
            
    def createProfileList(spawner):
        username = spawner.user.name
        userdn = os.environ.get(username)
        list = []
       
        #if('Personal' in userdn and 'IMA' in userdn):
        if('IMA16' in userdn):
          spawner.environment = {
              'CONFIGPATH' : '/tmp/exchange/ima/nbgrader_config.py'
              }
          list = [
              {
                'display_name': 'IMA Teacher Notebook',
                'default': True,
                'kubespawner_override': {
                  'image_spec': 'skogelnik/kuberhub-teacher-image:latest',
                  'cpu_guarantee': 0.5,
                  'cpu_limit': 1,
                  'mem_guarantee': '1G',
                  'mem_limit': '2G',
                }
              }
          ]
        #elif('IMA18' in userdn):
        elif('kuberhub' in userdn):
          list = [
              {
                'display_name': 'IMA Student Notebook',
                'default': True,
                'kubespawner_override': {
                  'image_spec': 'skogelnik/kuberhub-student-image:latest',
                  'cpu_guarantee': 0.5,
                  'cpu_limit': 1,
                  'mem_guarantee': '1G',
                  'mem_limit': '2G',
                }
              }
          ]
        #elif('PERSONAL' in userdn and 'DAT' in userdn):
        elif('kuberhub' in userdn):
          spawner.environment = {
              'CONFIGPATH' : '/tmp/exchange/dat/nbgrader_config.py'
            } 
          list = [
              {
                'display_name': 'Teacher Notebook',
                'default': True,
                'kubespawner_override': {
                  'image_spec': 'grainerm/teacher-datascience-notebook:latest',
                  'cpu_guarantee': 0.5,
                  'cpu_limit': 1,
                  'mem_guarantee': '1G',
                  'mem_limit': '2G',
                 }
              }
          ]
          
        elif('DAT18' in userdn):
          spawner.environment = {
              'CONFIGPATH' : '/tmp/exchange/dat/nbgrader_config.py'
            } 
          list = [
              {
                'display_name': 'Teacher Notebook',
                'default': True,
                'kubespawner_override': {
                  'image_spec': 'grainerm/student-datascience-notebook:latest',
                  'cpu_guarantee': 0.5,
                  'cpu_limit': 1,
                  'mem_guarantee': '1G',
                  'mem_limit': '2G',
                 }
              }
            ]  
        return list

    c.KubeSpawner.pre_spawn_hook = chooseImage

    c.KubeSpawner.start_timeout = 60 * 5  

    c.KubeSpawner.profile_list = createProfileList
   
    c.KubeSpawner.volumes = [
        {
          'name': 'nbgrader',
          'persistentVolumeClaim': {
             'claimName': 'nbgrader'
           }
        },
        {
          'name': 'users',
          'persistentVolumeClaim': {
             'claimName': 'claim-{username}'
           }
        }
     ]
    c.KubeSpawner.volume_mounts = [
        {
          'mountPath': '/tmp/exchange',
          'name': 'nbgrader'
        },
        {
          'mountPath': '/home/jovyan/work',
          'name': 'users'
        }
     ]
    c.KubeSpawner.http_timeout = 120
    
    c.KubeSpawner.cmd = ["/usr/local/bin/start.sh"] 
    
    c.KubeSpawner.node_affinity_preferred = [
        {
          'weight': 50,
          'preference': {
            'matchExpressions': [
                {
                  'key': 'node-role.kubernetes.io/master',
                  'operator': 'DoesNotExist',
                  'values': []
                }
            ]
          }
        }
    ]

singleuser:  
  image:
    pullPolicy: Always
  lifecycleHooks:
    postStart:
      exec: 
        command:
          - "bash"
          - "-c"
          - sh /tmp/exchange/post_start.sh
  uid: 0
  extraEnv:
    PYTHONPATH: "/opt/conda/bin"
  
