apiVersion: v1
kind: PersistentVolume
metadata:
  name: nbgrader
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/kuberhub/nfs/nbgrader
    server: 10.15.198.235
    readOnly: false
