apiVersion: v1
kind: PersistentVolume
metadata:
  name: nbgradernew
  namespace: jhub-8
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/salho/nfs/nbgrader
    server: 10.25.2.35
    readOnly: false
