kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nbgradernew
  namespace: jhub-8
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
