apiVersion: v1
kind: PersistentVolume
metadata:
  name: nbgrader
  namespace: jhub
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/kuberhub/nfs/nbgrader
    server: nfs_share
    readOnly: false
