apiVersion: v1
kind: PersistentVolume
metadata:
  name: jhub-hubdb
spec:
  storageClassName: “”
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/kuberhub/nfs/users
    server: 10.15.198.235
    readOnly: false
