apiVersion: v1
kind: PersistentVolume
metadata:
  name: jhub-hubdb
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/salho/nfs/users
    server: nfs_share
    readOnly: false
